# make all Java programs
#
#   Robert A. Dalrymple
#   Center for Applied Coastal Research
#   University of Delaware
#   Newark, DE 19716
#   (302) 831 2440  FAX 302 831 1228
#   rad@udel.edu
#
    
JFILES=		Array.java LinearPlot.java Bathymetry.java Beach.java \
		EdgeTheory.java Eigenmatrix.java ErrorFunction.java \
		Gauss.java Groin.java Hyper.java  Laguerre.java \
		OneLine.java Refract.java Sand.java Seiche.java StArray.java\
		Stream1.java Streamless.java Streamout.java Wave.java\
		Wvnumev.java DualFlap.java WaveTheory.java Wavemaker.java \
		Inlet.java Tide.java


all: 		
		/usr/local/java/bin/javac  $(JFILES)
